/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#004e9f',
        'primary-container': '#0066cc',
        surface: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        tertiary: '#883700',
        'tertiary-container': '#af4900',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb692',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-surface': '#191c1e',
        'on-surface-variant': '#414753',
        outline: '#727784',
        'outline-variant': '#c1c6d5',
        secondary: '#525f73',
        'secondary-container': '#d6e3fb',
        'secondary-fixed': '#d6e3fb',
        'secondary-fixed-dim': '#bac7de',
        'on-primary': '#ffffff',
        'on-primary-container': '#dfe8ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#586579',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffe3d6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#aac7ff',
        'primary-fixed': '#d7e3ff',
        'primary-fixed-dim': '#aac7ff',
        'on-primary-fixed': '#001b3e',
        'on-primary-fixed-variant': '#00458e',
        'on-secondary-fixed': '#0f1c2d',
        'on-secondary-fixed-variant': '#3b485a',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#793000',
        'surface-tint': '#005cba',
        // Manter cores galaxy existentes
        galaxy: {
          900: '#0a0a1a',
          800: '#12122a',
          700: '#1a1a3e',
          600: '#252555',
          500: '#3d3d7a',
          400: '#5c5c9e',
          300: '#8585c4',
          200: '#b3b3e0',
          100: '#d9d9f0',
        },
        nebula: {
          500: '#7c3aed',
          400: '#a78bfa',
        },
        star: {
          500: '#fbbf24',
          400: '#fcd34d',
        },
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '1.5rem': '1.5rem',
        '2rem': '2rem',
        full: '9999px',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(124, 58, 237, 0.5)' },
          '100%': { boxShadow: '0 0 20px rgba(124, 58, 237, 0.8)' },
        },
      },
    },
  },
  plugins: [],
}
